"""JSON serialization utilities for the SyntheticTrip schema.

The functions here build a dictionary that matches the ``SyntheticTrip``
Pydantic model defined in ``backend/models.py`` and then write it to a file.
"""

from datetime import datetime
from typing import List, Tuple

from .gps import add_gps_noise, bearing, haversine

def build_trip_json(
    trip_id: str,
    origin: Tuple[float, float],
    destination: Tuple[float, float],
    start_time: datetime,
    points: List[Tuple[float, float, int]],
) -> dict:
    """Construct the payload that conforms to ``SyntheticTrip``.
    ``points`` is a list of ``(lat, lon, timestamp)`` generated by
    ``interpolate_line``.
    """
    trace = []
    for idx, (lat, lon, ts) in enumerate(points):
        noisy_lat, noisy_lon = add_gps_noise(lat, lon)
        # Bearing towards the next point (or 0 for the last point)
        if idx < len(points) - 1:
            hdg = bearing((lat, lon), (points[idx + 1][0], points[idx + 1][1]))
            spd = haversine((lat, lon), (points[idx + 1][0], points[idx + 1][1]))
        else:
            hdg = 0.0
            spd = 0.0
        trace.append({
            "timestamp": ts,
            "lat": noisy_lat,
            "lon": noisy_lon,
            "heading": hdg,
            "speed": spd,
        })
    duration = points[-1][2] if points else 0
    return {
        "trip_id": trip_id,
        "metadata": {
            "origin": {"lat": origin[0], "lon": origin[1]},
            "destination": {"lat": destination[0], "lon": destination[1]},
            "start_time": start_time.isoformat(),
            "duration_seconds": duration,
            "profile": "stub",
        },
        "trace": trace,
    }
